/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'modamint': {
          50: '#fff8f6',
          100: '#ffeee9',
          200: '#ffddd6',
          300: '#ffbeb1',
          400: '#ff9582',
          500: '#ff6347',
          600: '#e94a29',
          700: '#c73915',
          800: '#a52f0f',
          900: '#8a2a0f',
        }
      }
    },
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [{
        modamint: {
          "primary": "#ff6347",
          "primary-focus": "#e94a29",
          "primary-content": "#ffffff",
          "secondary": "#ff9582",
          "secondary-focus": "#ff7f50",
          "secondary-content": "#ffffff",
          "accent": "#ffbeb1",
          "accent-focus": "#ffa394",
          "accent-content": "#1f2937",
          "neutral": "#3d4451",
          "neutral-focus": "#2a2e37",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f9fafb",
          "base-300": "#f3f4f6",
          "base-content": "#1f2937",
          "info": "#3abff8",
          "success": "#36d399",
          "warning": "#fbbd23",
          "error": "#f87272",
        },
      },
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
  },
}